sudo: required
language: cpp
dist: trusty
before_script:
  - qmake
script:
  - make
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt update -qq
  - sudo apt install -y libtag1-dev qtbase5-dev
