name: picaster
version: 2
summary: PiCaster is a podcasting software
description: A simple podcasting software

apps:
  picaster:
    command: qt5-launch picaster
    plugs:
      - home

parts:
  picaster:
    plugin: qmake
    source: ./
    build-packages:
      - qtbase5-dev
      - libtag1-dev
      - libasound2-dev
      - libjack-jackd2-dev
    stage-packages:
      # Here for the plugin
      - libqt5gui5
    after: [qt5conf]

